name: Deploy an App Engine app
'on':
  push:
    branches:
      - bub-new-squad
    # paths:
    #   - "app-engine/**"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - id: Bash
        run: |
          echo "A initial message"
          ls -ltr
      - uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.gcp_project }}
          working_directory: ./app-engine
          deliverables: app.yaml
          credentials: ${{ secrets.gcp_credentials }}