name: Deploy an App Engine app
'on':
  push:
    branches:
      - bub-new-squad
    # paths:
    #   - "app-engine/**"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app-engine
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: 'echo "$SSH_KEY" > ./data/serviceAccountKey.json'
        shell: bash
        env:
          SSH_KEY: ${{secrets.gcp_credentials}}
      - uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.gcp_project }}
          working_directory: ./app-engine
          deliverables: app.yaml
          credentials: ${{ secrets.gcp_credentials }}