name: lambda-depl

on:
  push:
    branches:
      - bub-new-squad

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lol-clash-roles
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: build
        run: mkdir ./dist && cp ./index.js ./dist/index.js
      - name: Install dependencies, Build application and Zip dist folder contents
        run: zip -j deploy.zip ./dist/*
      - name: test
        run: ls -ltr 