name: lambda-depl

on:
  push:
    branches:
      - bub-new-squad

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lol-clash-roles
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: ls -ltr 
      - name: build
        run: mkdir ./dist && cp ./index.js ./dist/index.js
      - name: Install dependencies, Build application and Zip dist folder contents
        run: zip -qq -r -j ./bundle.zip ./dist/*
      - name: test
        run: ls -ltr 
      - name: deploy zip to aws lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: lol-clash-roles
          zip_file: ./bundle.zip